### ISSUE TITLE
Refer the version field in metadata to the spec version

### ISSUE THREAD

**Issue by ChihChengLiang** [ethereum/eth2.0-test-generators#27]
There's a version field in the metadata. Not sure if it's meaningful to assign a version number to every test suite. However, it's useful to track what spec version the test suite is implemented.

Before:
```
metadata = {
        'title': 'Shuffling Algorithm Tests 1',
        'summary': 'Test vectors for validator shuffling with different validator\'s activity status.'
                   ' Note: only relevant validator fields are defined.',
        'test_suite': 'shuffle',
        'fork': 'tchaikovsky',
        'version': 1.0
    }
```
After:
```
metadata = {
        'title': 'Shuffling Algorithm Tests 1',
        'summary': 'Test vectors for validator shuffling with different validator\'s activity status.'
                   ' Note: only relevant validator fields are defined.',
        'test_suite': 'shuffle',
        'fork': 'tchaikovsky',
        'spec_version': 0.4.0
    }
```

**Comment by jannikluhn** [comment]
Should we maybe just drop `version` and use `fork` instead? Btw, what exactly does `tchaikovsky` refer to right now?

**Comment by ChihChengLiang** [comment]
Do you mean write spec version in the field `fork`?
I'm also curious about `tchaikovsky` too 😂

**Comment by jannikluhn** [comment]
yes, maybe with some prefix, like `phase0-0.5.0`

**Comment by djrtwo** [comment]
`tchaikovsky` was a stub from the original sample format :)

The distinction between `version` and `fork` is probably not really meaningful.  I believe using just `fork` makes sense.

**Comment by ChihChengLiang** [comment]
Add a pull request to specify `fork:phase0-0.5.0`
